// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';

import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB7Av1rG_h9Bx3gk9DWFE2lTE7sC4KUPA',
    appId: '1:232448418503:web:b8792ddd030b6741bc94e2',
    messagingSenderId: '232448418503',
    projectId: 'marketcheap-fa9ff',
    authDomain: 'marketcheap-fa9ff.firebaseapp.com',
    storageBucket: 'marketcheap-fa9ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXu5axKMkaG4w8ycCKtXWdZg_VzV0-DVg',
    appId: '1:232448418503:android:36f08cea9b107b47bc94e2',
    messagingSenderId: '232448418503',
    projectId: 'marketcheap-fa9ff',
    storageBucket: 'marketcheap-fa9ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOKkeejLKTeSRTv4QkK6-e6OjGC0rAQwk',
    appId: '1:232448418503:ios:ee86d06f54ae74fdbc94e2',
    messagingSenderId: '232448418503',
    projectId: 'marketcheap-fa9ff',
    storageBucket: 'marketcheap-fa9ff.firebasestorage.app',
    iosBundleId: 'com.example.marketcheap',
  );
}
