// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1CJoSc6v7rM-cWcIJEgw6b5zkJ19qkoM',
    appId: '1:797435647849:web:c35270ecfecdacef580ff8',
    messagingSenderId: '797435647849',
    projectId: 'marketcheap-fe3be',
    authDomain: 'marketcheap-fe3be.firebaseapp.com',
    storageBucket: 'marketcheap-fe3be.firebasestorage.app',
    measurementId: 'G-H710TDQ7Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiR43AauAHSuvy2T6Ut6MZX8cZFRZgAMg',
    appId: '1:797435647849:android:8c539edb3c12ee49580ff8',
    messagingSenderId: '797435647849',
    projectId: 'marketcheap-fe3be',
    storageBucket: 'marketcheap-fe3be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVy_gyLrNYpWTlE4cxN7WnLtZUWP7PQOg',
    appId: '1:797435647849:ios:75879f1802e5ae4f580ff8',
    messagingSenderId: '797435647849',
    projectId: 'marketcheap-fe3be',
    storageBucket: 'marketcheap-fe3be.firebasestorage.app',
    iosBundleId: 'com.example.marketcheap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVy_gyLrNYpWTlE4cxN7WnLtZUWP7PQOg',
    appId: '1:797435647849:ios:75879f1802e5ae4f580ff8',
    messagingSenderId: '797435647849',
    projectId: 'marketcheap-fe3be',
    storageBucket: 'marketcheap-fe3be.firebasestorage.app',
    iosBundleId: 'com.example.marketcheap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1CJoSc6v7rM-cWcIJEgw6b5zkJ19qkoM',
    appId: '1:797435647849:web:e2d1b7f494484143580ff8',
    messagingSenderId: '797435647849',
    projectId: 'marketcheap-fe3be',
    authDomain: 'marketcheap-fe3be.firebaseapp.com',
    storageBucket: 'marketcheap-fe3be.firebasestorage.app',
    measurementId: 'G-5H88WKSLMV',
  );
}
